#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This dictionary provides a mapping for the L'Annee Philologique journal abbreviations.
""" 

{
    "A&A": "Antike und Abendland: Beitr\u00e4ge zum Verst\u00e4ndnis der Griechen und R\u00f6mer und ihre Nachlebens",
    "A&R": "Atene e Roma: rassegna trimestrale dell'Associazione Italiana di Cultura classica",
    "AA": "Arch\u00e4ologischer Anzeiger",
    "AAAD": "Antichit\u00e0 altoadriatiche",
    "AAAH": "Acta ad archaeologiam et artium historiam pertinentia",
    "AAASzeged": "Acta Univ. de Attila J\u00f3zsef nominatae, Acta antiqua et archaeologica.",
    "AABS": "Annuaire des amis de la Biblioth\u00e8que de S\u00e9lestat",
    "AAEC": "Annuario dell'Accademia etrusca di Cortona",
    "AAHG": "Anzeiger f\u00fcr die Altertumswissenschaft, hrsg. von der \u00d6sterreichischen Humanistischen Gesellschaft",
    "AALIG": "Atti dell'Accademia Ligure di Scienze e Lettere",
    "AAMed": "Atti della Accademia Mediterranea delle Scienze",
    "AAN": "Atti della Accademia di Scienze morali e politiche della Societ\u00e0 nazionale di Scienze, Lettere ed Arti di Napoli",
    "AAntHung": "Acta Antiqua Academiae Scientiarum Hungaricae",
    "AAP": "Atti dell'Accademia Pontaniana",
    "AAPal": "Atti dell'Accademia di Scienze, Lettere e Arti di Palermo",
    "AAPat": "Atti e Memorie dell'Accademia Patavina di Scienze, Lettere ed Arti, Classe di Sc. mor., Lett. ed Arti",
    "AAPel": "Atti della Accademia Peloritana dei Pericolanti, Classe di Lettere, Filosofia e Belle Arti",
    "AArch": "Acta Archaeologica",
    "AArchHung": "Acta Archaeologica Academiae Scientiarum Hungaricae",
    "AArchSlov": "Acta Archaeologica (Arheoloski Vestnik)",
    "AARov": "Atti della Accademia Roveretana degli Agiati, Classe di Scienze umane, Lettere ed Arti",
    "AASO": "The Annual of the American Schools of Oriental Research",
    "AAT": "Atti della Accademia delle Scienze di Torino, Classe di Scienze morali, storiche e filologiche",
    "AATC": "Atti e Memorie dell'Accademia Toscana La Colombaria",
    "AAWM": "Abhandlungen der Akademie der Wissenschaften in Mainz, Geistes und sozialwissenschaftliche Klasse",
    "AAWW": "Anzeiger der \u00d6sterreichischen Akademie der Wissenschaften in Wien, Philos.-Hist. Klasse",
    "AB": "Analecta Bollandiana",
    "ABAW": "Abhandlungen der Bayerischen Akademie der Wissenschaften, Philos.-Hist. Klasse",
    "ABG": "Archiv f\u00fcr Begriffsgeschichte: Bausteine zu einem historischen W\u00f6rterbuch der Philosophie",
    "ABPO": "Annales de Bretagne et des Pays de l'Ouest",
    "ABSA": "Annual of the British School at Athens",
    "ABull": "The Art Bulletin: a quarterly published by the College Art Association of America",
    "AC": "L'Antiquit\u00e9 classique",
    "ACD": "Acta classica Universitatis Scientiarum Debreceniensis",
    "ACF": "Annuaire du Coll\u00e8ge de France",
    "AClass": "Acta classica: proceedings of the Classical Association of South Africa",
    "AD": "Archaiologikon Deltion",
    "ADFF": "Annali del Dipartimento di filosofia dell'Universit\u00e0 di Firenze",
    "ADSV": "Anticnaja drevnost'i srednije veka (L'antiquit\u00e9 et le Moyen \u00c2ge)",
    "AE": "Archaiologike Ephemeris",
    "AEA": "Archivo Espa\u00f1ol de Arqueolog\u00eda",
    "AEH": "Argeion oikonomikes istorias (Archives of Economic History, Athens)",
    "AEHE IV": "Annuaire de l'\u00e9cole pratique des Hautes \u00e9tudes, IV' sect., Sciences hist. & philol",
    "AEHE V": "Annuaire de l'\u00e9cole pratique des Hautes \u00e9tudes, Ve sect., Sciences religieuses",
    "AEph": "Archaiologike ephemeris",
    "AErt": "Archaeologiai Ertesit\u00f6",
    "Aevum(ant)": "Aevum antiquum",
    "AFB": "Anuari de filologia, Secci\u00f3 D, Studia Graeca et Latina",
    "AFC": "Anales de Filologia cl\u00e1sica",
    "AFGG": "Annali della Facolt\u00e0 di Giurisprudenza, Universit\u00e0 di Genova",
    "AFLB": "Annali della Facolt\u00e0 di Lettere e Filosofia di Bari",
    "AFLC": "Annali della Facolt\u00e0 di Lettere e Filosofia della Universit\u00e0 di Cagliari",
    "AFLD": "Annales de la Facult\u00e9 des Lettres et Sciences humaines de l'Universit\u00e9 de Dakar",
    "AFLL": "Annali della Facolt\u00e0 di Lettere di Lecce",
    "AFLM": "Annali della Facolt\u00e0 di Lettere e Filosofia, Universit\u00e0 di Macerata",
    "AFLN": "Annali della Facolt\u00e0 di Lettere e Filosofia della Universit\u00e0 di Napoli",
    "AFLPer": "Annali della Facolt\u00e0 di Lettere e Filosofia di Perugia",
    "AFLS": "Annali della Facolt\u00e0 di Lettere e Filosofia dell'Universit\u00e0 di Siena",
    "AFMC": "Annali della Facolt\u00e0 di Magistero dell'Universit\u00e0 di Cagliari",
    "AFSFC": "Annali della Facolt\u00e0 di Scienze della Formazione dell'Universit\u00e0 di Cagliari",
    "AGI": "Archivio Glottologico Italiano",
    "AGLComo": "Annuario del Ginnasio Liceo A. Volta di Como",
    "AGPh": "Archiv f\u00fcr Geschichte der Philosophie",
    "AGR": "Akten der Gesellschaft f\u00fcr griechische und hellenistische Rechts- geschichte",
    "AH": "Ancient History",
    "AHAM": "Anales de Historia antigua y medieval",
    "AHAUSJ": "Annales d'histoire et d'arch\u00e9ologie / Universit\u00e9 Saint-Joseph",
    "AHAW": "Abhandlungen der Heidelberger Akademie der Wissenschaften, Philos.- Hist. Klasse",
    "AHB": "The Ancient History Bulletin",
    "AHC": "Annuarium Historiae Conciliorum",
    "AHDE": "Anuario de Historia del Derecho Espa\u00f1ol",
    "AHES": "Archive for history of exact sciences",
    "AHistHung": "Acta Historica Academiae Scientiarum Hungaricae",
    "AHMA": "Archives d'histoire doctrinale et litt\u00e9raire du Moyen \u00c2ge",
    "AHR": "American Historical Review",
    "AHSzeged": "Acta Univ. de Attila Jozsef nominatae, Acta Historica",
    "AI": "Acta Iranica: encyclop\u00e9die permanente des \u00e9tudes iraniennes",
    "AIHS": "Archives internationales d'histoire des sciences",
    "AIIN": "Annali dell'Istituto Italiano di Numismatica",
    "AIIS": "Annali dell'Istituto Italiano per gli Studi Storici",
    "AION(archeol)": "Annali dell'Istituto universitario orientale di Napoli, Dipartimento di studi del mondo classico e del Mediterraneo antico, Sezione di archeologia e storia antica",
    "AION(filol)": "Annali dell'Istituto universitario orientale di Napoli, Dipartimento di studi del mondo classico e del Mediterraneo antico, Sezione filologico-letteraria",
    "AION(ling)": "Annali dell'Istituto universitario orientale di Napoli, Dipartimento di studi del mondo classico e del Mediterraneo antico, Sezione linguistica",
    "AIPh": "Annales de l'Institut de philosophie",
    "AIPhO": "Annuaire de l'Institut de Philologie et d'Histoire Orientales et Slaves de l'Universit\u00e9 Libre de Bruxelles",
    "AISF": "Annali dell'Istituto di Storia, Univ. di Firenze",
    "AIV": "Atti dell'Istituto Veneto di Scienze, Lettere ed Arti, Classe di Scienze morali e Lettere",
    "AJ": "The Archaeological Journal",
    "AJA": "American Journal of Archaeology",
    "AJAH": "American Journal of Ancient History",
    "AJN": "American Journal of Numismatics",
    "AJPh": "American Journal of Philology",
    "AK": "Antike Kunst, hrsg. von der Vereiningung der Freunde antiker Kunst",
    "AKB": "Arch\u00e4ologisches Korrespondenzblatt: Urgeschichte, R\u00f6merzeit, Fr\u00fchmittelalter",
    "AKBern": "Arch\u00e4ologie im Kanton Bern: Fundberichte und Aufs\u00e4tze",
    "AKG": "Archiv f\u00fcr Kulturgeschichte",
    "Akroterion": "Akroterion: quarterly for the Classics in South Africa",
    "Alba Regia": "Alba Regia: annales Musei Stephani Regis",
    "ALGP": "Annali del Liceo classico G. Garibaldi di Palermo",
    "ALMA": "Archivum Latinitatis Medii Aevi (Bulletin Du Cange)",
    "ALMArv": "Annales Latini Montium Arvernorum: bulletin du Groupe d'\u00e9tudes latines de l'Universit\u00e9 de Clermont",
    "Altertum": "Das Altertum, hrsg. vom Zentralinst. f\u00fcr Alte Gesch. und Arch\u00e4ol. der Dt. Akad. der DDR",
    "AMA": "Anticnyj mir i arkheologija (Le monde antique et l'arch\u00e9ologie)",
    "AMal": "Analecta Malacitana: revista de la Secci\u00f3n de Filolog\u00eda de la Facultad de Filosof\u00eda y Letras",
    "AMArc": "Atti e Memorie dell'Arcadia",
    "AMAV": "Atti e Memorie delle Accademie di Agricoltura, Scienze e Lettere di Verona",
    "AMSI": "Atti e Memorie della Societ\u00e0 Istriana di Archeologia e Storia Patria",
    "AMW": "Archiv f\u00fcr Musikwissenschaft",
    "AN": "Aquileia nostra: bolletino dell'Associazione nazionale per Aquileia",
    "AncPhil": "Ancient Philosophy",
    "AncSoc": "Ancient Society",
    "AncW": "The Ancient World",
    "Annales (ESC)": "Annales: \u00e9conomies, soci\u00e9t\u00e9s, civilisations",
    "Annales (HSS)": "Annales: histoire, sciences sociales",
    "AnnEpigr": "L'Ann\u00e9e \u00e9pigraphique",
    "AnnNorm": "Annales de Normandie",
    "AnnSE": "Annali di storia dell'esegesi",
    "ANRW": "Aufstieg und Niedergang der r\u00f6mischen Welt: Geschichte und Kultur Roms im Spiegel der neueren Forschung",
    "AntAfr": "Antiquit\u00e9s africaines",
    "AntJ": "The Antiquaries Journal: being the Journal of the Society of Antiquaries of London",
    "AOF": "Archiv f\u00fcr Orientforschung: Internationale Zeitschrift f\u00fcr die Wissenschaft vom Vorderen Orient",
    "AOrientHung": "Acta Orientalia Academiae Scientiarum Hungaricae",
    "APF": "Archiv f\u00fcr Papyrusforschung und verwandte Gebiete",
    "APh": "L'Ann\u00e9e Philologique",
    "APhD": "Archives de philosophie du droit",
    "APhQ": "American Philosophical Quarterly",
    "AR": "Archaeological Reports",
    "ArchClass": "Archeologia classica: rivista della Scuola naz. di Archeologia, pubbl. a cura degli Ist. di Archeologia e Storia dell'arte greca e romana e di Etruscologia e antichit\u00e0 italiche dell'Univ. di Roma",
    "ArchN": "Archaeological news",
    "ArchOrient": "Archiv orient\u00e1ln\u00ed",
    "ArchPhilos": "Archives de philosophie: recherches et documentation",
    "ArchS": "Arch\u00e4ologie der Schweiz: Mitteilungsblatt der Schweizerischen Gesellschaft f\u00fcr Ur- und Fr\u00fchgeschichte",
    "ARH": "Arheologi\u00e2, publ. par l'Inst. d'Arch\u00e9ol. de l'Acad. des Sciences d'Ukraine et par la Soc. ukrainienne pour la pr\u00e9servation des monuments culturels et historiques",
    "ARID": "Analecta Romana Instituti Danic",
    "AS": "Anatolian Studies: journal of the British Inst. of Archaeology at Ankara",
    "ASAA": "Annuario della Scuola Archeologica di Atene a delle Missioni Italiane in Oriente",
    "ASAE": "Annales du Service des Antiquit\u00e9s d'\u00e9gypte",
    "ASAW": "Abhandlungen der S\u00e4chsischen Akademie der Wissenschaften zu Leipzig",
    "ASCL": "Archivio Storico per la Calabria e la Lucania",
    "ASE": "Anglo-Saxon England",
    "ASGM": "Atti del Sodalizio glottologico milanese",
    "ASGP": "Annali del Seminario Giuridico dell'Univ. di Palermo",
    "ASMG": "Atti e memorie della Societ\u00e0 Magna Grecia",
    "ASNP": "Annali della Scuola Normale Superiore di Pisa, Cl. di Lettere e Filosofia",
    "ASP": "Archivio Storico Pugliese",
    "ASSARD": "Archivio Storico Sardo",
    "ASTADT": "Die Alte Stadt: Vierteljahreszeitschrift f\u00fcr Stadtgeschichte, Stadtsoziologie und Denkmalpflege",
    "AU": "Der altsprachliche Unterricht: Arbeitshefte zu seiner wissenschaftlichen Begr\u00fcndung und praktischen Gestalt",
    "AUB(class)": "Annales Universitatis Budapestinensis de Rolando E\u00f6tv\u00f6s nominatae, Sectio classica",
    "AUB(phil)": "Annales Universitatis Budapestinensis de Rolando E\u00f6tv\u00f6s nominatae, \u00ca Sectio philosophica et sociologica",
    "AUBFjur.)": "Annales Universitatis Budapestinensis de Rolando E\u00f6tv\u00f6s nominatae, \u00ca Sectio iuridica",
    "AUFG": "Annali dell'Universit\u00e0 di Ferrara, Sez. V, Sc. giurid",
    "AugAge": "Augustan Age",
    "AugStud": "Augustinian Studies",
    "AUM": "Anales de la Universidad de Murcia, Facultad de Letras",
    "AUMLA": "Journal of the Australasian Universities Language and Literature Association",
    "AUS": "Annuaire de l'Universit\u00e9 de Sofia, Facult\u00e9 des Lettres",
    "AV": "Annales Valaisannes",
    "AVM": "Atti e memorie della Accademia Virgiliana di Mantova",
    "AW": "Antike Welt",
    "AZP": "Allgemeine Zeitschrift f\u00fcr Philosophie",
    "B&W": "Bibliothek und Wissenschaft",
    "BA": "Bollettino d'arte del Ministero per i beni culturali e ambientali",
    "BAA": "Bulletin d'arch\u00e9ologie alg\u00e9rienne",
    "BAB": "Bulletin de la Classe des Lettres de l'Acad\u00e9mie Royale de BelgiqueN",
    "BABesch": "Bulletin Antieke Beschaving",
    "BAGB": "Bulletin de l'Association Guillaume Bud\u00e9",
    "BAL": "Bulletin des antiquit\u00e9s luxembourgeoises",
    "BAM": "Bulletin d'arch\u00e9ologie marocaine",
    "BASO": "Bulletin of the American Schools of Oriental Research in Jerusalem and Baghdad",
    "BASP": "Bulletin of the American Society of Papyrologists",
    "BAVA": "Beitr\u00e4ge zur allgemeinen und vergleichenden Arch\u00e4ologie",
    "BCAR": "Bullettino della Commissione Archeologica Comunale in Roma",
    "BCH": "Bulletin de correspondance hell\u00e9nique",
    "BCPE": "Bolletino del Centro Inernazionale per lo Studio dei Papyri Ercolanesi (Cronache Ercolanesi)",
    "BCTH": "Bulletin arch\u00e9ologique du Comit\u00e9 des travaux historique",
    "BECh": "Biblioth\u00e8que de l'\u00e9cole des Chartes",
    "BEO": "Bulletin d'\u00e9tudes orientales, publi\u00e9 par l'Institut Fran\u00e7ais de Damas",
    "BES": "Bulletin of the Egyptological Seminar",
    "BFLM": "Bulletin de la Facult\u00e9 des Lettres de Mulhouse",
    "BHM": "Bulletin of the History of Medicine",
    "BIAL": "Bulletin of the Institute of Archaeology of the Univ. of London",
    "BIAO": "Bulletin de l'Institut fran\u00e7ais d'arch\u00e9ologie orientale",
    "BiblH&R": "Biblioth\u00e8que d'humanisme et Renaissance",
    "BIBR": "Bulletin de l'Institut historique belge de Rome",
    "BICS": "Bulletin of the Institute of Classical Studies of the University of London",
    "BIDR": "Bullettino dell'Istituto di Diritto romano",
    "BiZ": "Biblische Zeitschrift (Neue Folge)",
    "BJ": "Bonner Jahrb\u00fccher des Rheinischen Landesmuseums in Bonn und des Vereins von Altertumsfreunden im Rheinlande",
    "BJHP": "British Journal for the History of Philosophy",
    "BJHS": "British Journal for the History of Science",
    "BLE": "Bulletin de litt\u00e9rature eccl\u00e9siastique",
    "BLR": "The Bodleian Library Record",
    "BMAH": "Bulletin des Mus\u00e9es royaux d'Art et d'Histoire",
    "BMAN": "Bolet\u00edn del Museo arqueol\u00f3gico nacional",
    "BMB": "Bulletin du Mus\u00e9e de Beyrouth",
    "BMCRev": "Bryn Mawr Classical Review",
    "BMM": "Bulletin of the Metropolitan Museum of Art",
    "BMMP": "Bollettino dei monumenti, musei e gallerie pontificie",
    "BMNE": "Bulletin of the Museum of Mediterranean and Near Eastern Antiquities",
    "BMUSUM": "Bulletin of the Museums of Art and Archaeology of the University of Michigan",
    "BMZ": "Museo de Zaragoza, Bolet\u00edn",
    "BN": "Beitr\u00e4ge zur Namenforschung",
    "BNum": "Bollettino di numismatica",
    "BO": "Bibliotheca Orientalis, uitg. van het Nederlandsch Instituut voor het Nabije Oosten",
    "BollClass": "Bollettino dei classici, a cura del Comitato per la preparazione dell'Edizione nazionale dei Classici greci e latini",
    "BPHM": "Bulletin de la Soci\u00e9t\u00e9 internationale pour l'\u00e9tude de la philosophie m\u00e9di\u00e9vale",
    "BRGK": "Bericht der R\u00f6misch-Germanischen Kommission des Deutschen Arch\u00e4ologischen Instituts",
    "BritAA": "British Archaeological Abstracts",
    "BritAB": "British Archaeological Bibliography",
    "BRL": "Bulletin of the John Rylands Library",
    "BSAF": "Bulletin de la Soci\u00e9t\u00e9 nationale des antiquaires de France",
    "BSAO": "Bulletins de la Soci\u00e9t\u00e9 des Antiquaires de l'Ouest",
    "BSAP": "Bulletins trimestriels de la Soci\u00e9t\u00e9 des antiquaires de Picardie",
    "BSEAA": "Bolet\u00edn del Seminario de Estudios de Arte y Arqueolog\u00eda",
    "BSFN": "Bulletin de la Soci\u00e9t\u00e9 fran\u00e7aise de numismatique",
    "BSL": "Bulletin de la Soci\u00e9t\u00e9 de linguistique de Paris",
    "BSPh": "Bulletin de la Soci\u00e9t\u00e9 fran\u00e7aise de philosophie",
    "BSTEC": "Bulletin de la Soci\u00e9t\u00e9 toulousaine d'\u00e9tudes classiques",
    "BStudLat": "Bollettino di studi latini: periodico quadrimestrale d'informazione bibliografica",
    "BTh": "Bulletin de th\u00e9ologie ancienne et m\u00e9di\u00e9vale",
    "BullAIEMA": "Bulletin d'information de l'Association internationale pour l'\u00e9tude de la mosa\u00efque antique",
    "BVBl": "Bayerische Vorgeschichtsbl\u00e4tter",
    "BWG": "Berichte zur Wissenschaftsgeschichte",
    "ByzF": "Byzantinische Forschungen: internationale Zeitschrift f\u00fcr Byzantinistik",
    "ByzSlav": "Byzantinoslavica: revue internationale des \u00e9tudes byzantines",
    "ByzZ": "Byzantinische Zeitschrift",
    "BZG": "Basler Zeitschrift f\u00fcr Geschichte und Altertumskunde",
    "C&M": "Classica et mediaevalia: revue danoise d'histoire et de philologie publi\u00e9e par la Soci\u00e9t\u00e9 danoise pour les \u00e9tudes anciennes et m\u00e9di\u00e9vales",
    "C&S": "Cultura e scuola",
    "CAAH": "Cahiers alsaciens d'arch\u00e9ologie, d'art et d'histoire",
    "CahNum": "Cahiers de Numismatique: bulletin de la Soci\u00e9t\u00e9 d'\u00e9tudes numismatiques et arch\u00e9ologiques",
    "CArch": "Cahiers arch\u00e9ologiques: fin de l'antiquit\u00e9 et Moyen \u00c2ge",
    "CB": "The Classical Bulletin",
    "CCC": "Civilt\u00e0 classica e cristiana",
    "CCEC": "Cahiers du Centre d'\u00e9tudes Chypriotes",
    "CCG": "Cahiers du Centre Gustave Glotz",
    "CCGR": "Cahiers du Centre Georges Radet",
    "CE": "Chronique d'Egypte",
    "CEA": "Cahiers des \u00e9tudes anciennes",
    "CEDAC": "Centre d'\u00e9tudes et de documentation arch\u00e9ologique de la Conservation de Carthage. Bulletin",
    "CFC(G)": "Cuadernos de filolog\u00eda cl\u00e1sica. Estudios griegos e indoeuropeos.",
    "CFC(L)": "Cuadernos de filolog\u00eda cl\u00e1sica. Estudios latinos.",
    "CFS": "Cahiers Ferdinand de Saussure: review suisse de linguistique g\u00e9n\u00e9rale",
    "CGITA": "Cahiers du groupe interdisciplinaire du th\u00e9\u00e2tre antique (Cahiers du GITA)",
    "CH": "Cahiers d'histoire publ. par les Univ. de Clermont-Lyon-Grenoble",
    "ChHist": "Church History",
    "CHR": "Catholic Historical Review",
    "CHum": "Computers and the Humanitie",
    "CIF": "Cuadernos de investigaci\u00f3n filol\u00f3gica",
    "CIMA": "Cahiers de l'Institut du Moyen \u00c2ge grec et latin",
    "CISA": "Contributi dell'Istituto di Storia antica dell'Univ. del Sacro Cuore",
    "CJ": "The Classical Journal",
    "CJPh": "Canadian Journal of Philosophy",
    "CL": "Corolla Londiniensis",
    "ClAnt": "Classical Antiquity",
    "Classica(Brasil)": "Classica: revista brasileira de estudos cl\u00e1ssicos",
    "Classica(Lisboa)": "Classica: Boletim de pedagogia e cultura",
    "ClassStud": "Classical Studies",
    "ClassWrat": "Acta Universitatis Wratislaviensis. Classica Wratislaviensia.",
    "CLS": "Comparative Literature Studies",
    "CM": "Clio Medica: acta Academiae internationalis historiae medicinae",
    "CML": "Classical and Modern Literature",
    "CO": "The Classical Outlook: journal of the American Classical League",
    "CodMan": "Codices manuscripti: Zeitschrift f\u00fcr Handschriftenkunde",
    "ColbyQ": "Colby Quarterly",
    "CompLit": "Comparative Literature",
    "ConnHell": "Connaissance hell\u00e9nique",
    "CPAC": "Cuaderns de prehist\u00f2ria i arqueologia de Castell\u00f3",
    "CPAM": "Cuadernos de prehistoria i arqueolog\u00eda",
    "CPh": "Classical Philology ",
    "CPhPJ": "Cahiers de philosophie politique et juridique",
    "CPhRev": "Canadian philosophical reviews",
    "CQ": "Classical Quarterly",
    "CR": "Classical Review",
    "CRAI": "Comptes rendus de l'Acad\u00e9mie des Inscriptions et Belles-Lettres",
    "CRCL": "Canadian review of comparative literature",
    "CRDAC": "Atti del Centro ricerche e documentazione sull'antichit\u00e0 classica",
    "CRIPEL": "Cahiers de recherches de l'Institut de Papyrologie et d'\u00e9gyptologie de Lille III",
    "CronErc": "Cronache Ercolanesi",
    "CrSt": "Cristianesimo nella storia: richerche storiche, esegetiche, teologiche",
    "CS": "Critica storica",
    "CSSH": "Comparative Studies in Society and History",
    "CT": "Les Cahiers de Tunisie",
    "CW": "The Classical World",
    "DA": "Dissertations Abstracts: international abstracts of dissertation available in microfilm or as xerographic reproductions",
    "DArch": "Dialoghi di archeologia",
    "DDJ": "Deutsches Dante-Jahrbuch",
    "DGT": "Drevnejsije Gosudarstva na territorii SSSR (Les \u00e9tats les plus anciens sur le territoire de l'URSS: mat\u00e9riaux et recherches)",
    "DHA": "Dialogues d'histoire ancienne",
    "DLZ": "Deutsche Literaturzeitung f\u00fcr Kritik der internationalen Wissenschaft",
    "DOP": "Dumbarton Oaks Papers",
    "DR": "Downside Review",
    "DUJ": "Durham University Journal",
    "E&W": "East and West",
    "EA": "Epigraphica Anatolica: Zeitschrift f\u00fcr Epigraphik und historische Geographie Anatoliens",
    "EAZ": "Ethnographisch-arch\u00e4ologische Zeitschrift",
    "EC": "\u00c9tudes celtiques",
    "ECl\u00e1s": "Estudios cl\u00e1sicos: organo de la Sociedad espanola de estudios cl\u00e1sicos",
    "EDT": "L'\u00c9crit du temps",
    "EEAth": "Epistemonike epeteris tes philosophikes Scholes tou Panepistemiou Athenon",
    "EEThess(philos)": "Epistemonike epeterida tes philosophikes Scholes tou Aristoteleiou Panepistemiou Thessalonikes, Tmema philosophias",
    "EHEM": "Epeteris tes Hetaireias Eleiakon Meleton",
    "EHHD": "Epeteris tes Kentrou Ereunes tes Historias tou Hellenikou Dikaiou",
    "EHR": "English Historical Review",
    "EHum": "Estudios humanisticos",
    "EIE": "\u00c9tudes indo-europ\u00e9ennes",
    "EL": "\u00c9tudes de lettres: bulletin de la Facult\u00e9 des Lettres de l'Univ. de Lausanne et de la Soc. des \u00e9tudes de Lettres",
    "ELF": "Ensaios de literatura e filologia, publ. do Dept. de Letras cl\u00e1ssicas, Fac. de Letras Univ. federal de Minas Gerais",
    "EMC": "\u00c9chos du monde classique (Classical Views)",
    "EPh": "\u00c9tudes philosophiques",
    "Eranos-Jb": "Eranos-Jahrbuch",
    "EstAnt": "Estudios de la antig\u00fcedad",
    "ETF(arqueol)": "Espacio, tiempo y forma: revista de la Facultad de Geograf\u00eda e Historia, Ser. 1",
    "ETF(hist)": "Espacio, tiempo y forma: revista de la Facultad de Geografia e Historia, Ser. 2",
    "EThL": "Ephemerides Theologicae Lovanienses",
    "EVO": "Egitto e Vicino Oriente",
    "ExcPhilol": "Excerpta philologica",
    "FAM": "Filologia antica e moderna",
    "FBSM": "Forschungen und Berichte, hrsg. von den Staatlichen Museen",
    "FBW": "Fundberichte aus Baden-W\u00fcrttemberg, hrsg. von Landesdenkmalamt",
    "FIul": "Forum Iulii: annuario del Museo archeologico nazionale di Cividale del Friuli",
    "FL": "Forum der Letteren",
    "FlorIlib": "Florentia Iliberritana",
    "FMS": "Fr\u00fchmittelalterliche Studien",
    "FNT": "Filolog\u00eda neotestamentaria",
    "FR": "Felix Ravenna",
    "FZPhTh": "Freiburger Zeitschrift f\u00fcr Philosophie und Theologie",
    "G&R": "Greece and Rome",
    "GB": "Grazer Beitr\u00e4ge: Zeitschrift f\u00fcr die klassische Altertumswissenschaft",
    "GCFI": "Giornale critico della filosofia italiana",
    "GeorgAnt": "Geographia Antiqua",
    "GFA": "G\u00f6ttinger Forum f\u00fcr Altertumswissenschaft",
    "GFRF": "Giornale ferrarese di retorica e filologia",
    "GGA": "G\u00f6ttingische Gelehrte Anzeigen",
    "GH": "Le Genre humain",
    "GIF": "Giornale italiano di filologia: rivista trimestrale di cultura",
    "GJ": "The Geographical Journal",
    "GLO": "Graecolatina et Orientalia: zborn\u00edk Filoz. Fak. Univerz. Komensk\u00e9ho",
    "GLP": "Graecolatina Pragensia: acta Universitatis Carolinae",
    "GM": "Giornale di metafisica",
    "GMusJ": "The J. Paul Getty Museum Journal",
    "GNS": "Gazette numismatique suisse",
    "GRBS": "Greek, Roman and Byzantine Studies",
    "GS": "German Studies: a review of German-language research contributions. Sect. l: Philosophy and history; 3: Literature, Music. Fine arts",
    "GWU": "Geschichte in Wissenschaft und Unterricht",
    "H&T": "History and Theory: studies in the philosophy of history ",
    "HA": "Helvetia archaeologica",
    "HAnt": "Hispania antiqua: revista de historia antigua",
    "HASB": "Hefte des Arch\u00e4ologischen Seminars der Universit\u00e4t Bern",
    "HBA": "Hamburger Beitr\u00e4ge zur Arch\u00e4ologie",
    "HBN": "Hamburger Beitr\u00e4ge zur Numismatik",
    "HebrUCA": "Hebrew Union College Annual",
    "HEL": "Histoire, \u00e9pist\u00e9mologie, langage",
    "Hellenica": "Hellenika: philol. histor. kai laogr. periodikon syngramma tes Hetaireias Makedonikon Spoudon",
    "HJ": "Historisches Jahrbuch",
    "HLB": "Harvard Library Bulletin",
    "HM": "Historia mathematica: international journal of the history of mathematics",
    "HPhQ": "History of Philosophy Quarterly",
    "HPLS": "History and Philosophy of the Life Sciences",
    "HPTh": "History of political thought",
    "HR": "History of Religions",
    "HS": "History of Science",
    "HSF": "Historische Sprachforschung (Historical Linguistics)",
    "HSMed": "Histoire des sciences m\u00e9dicales",
    "HSPh": "Harvard Studies in Classical Philology",
    "HTechn": "History of Technology",
    "HThR": "Harvard Theological Review",
    "HumLov": "Humanistica Lovaniensia",
    "HZ": "Historische Zeitschrift",
    "IA": "Iranica antiqua",
    "ICS": "Illinois Classical Studies",
    "IEJ": "Israel Exploration Journal",
    "IF": "Indogermanische Forschungen",
    "IFE": "Istoriko-filosofsky ezegodnik (History of philosophy yearbook), ed. by the Inst. of Philosophy of the Acad. of Sciences of URSS",
    "IG": "L'Information grammaticale",
    "IH": "L'Information historique",
    "IJCT": "International journal of the classical tradition",
    "IJNA": "International journal of nautical archaeology",
    "IJPS": "International journal of philosophical studies",
    "IL": "L'Information litt\u00e9raire",
    "ILing": "Incontri linguistici",
    "IMU": "Italia medioevale e umanistica",
    "InFil": "Inozemna filolog\u00ec\u00e2 (Philologie \u00e9trang\u00e8re)",
    "InvLuc": "Invigilata lucernis: rivista dell'Istituto di Latino",
    "IPQ": "International Philosophical Quarterly",
    "ISPh": "International Studies in Philosophy",
    "JA": "Journal asiatique",
    "JAC": "Journal of ancient civilizations",
    "JAK": "Jahresberichte aus Augst und Kaiseraugst",
    "JAOS": "Journal of the American Oriental Society",
    "JARCE": "Journal of the American Research Center in Egypt",
    "JAS": "Journal of the Royal Asiatic Society of Great Britain and Ireland",
    "JBAA": "The Journal of the British Archaeological Association",
    "JbAC": "Jahrbuch f\u00fcr Antike und Christentum",
    "JBerlM": "Jahrbuch der Berliner Museen",
    "JBL": "Journal of Biblical Literature",
    "JCS": "Journal of Classical Studies: the journal of the Class. Soc. of Japan",
    "JDAI": "Jahrbuch des Deutschen Arch\u00e4ologischen Instituts",
    "JEA": "Journal of Egyptian Archaeology",
    "JECS": "Journal of early Christian studies",
    "JEH": "Journal of Ecclesiastical History",
    "JESHO": "Journal of the economic and social history of the Orient",
    "JEurArch": "Journal of European archaeology",
    "JFA": "Journal of Field Archaeology",
    "JGRS": "Journal of Greco-Roman Studies",
    "JGS": "Journal of Glass Studies",
    "JHA": "Journal for the history of astronomy",
    "JHAS": "Journal for the history of Arabic science",
    "JHAW": "Jahrbuch der Heidelberger Akad. der Wissenschaften",
    "JHB": "Journal of the history of biology",
    "JHI": "Journal of the History of Ideas",
    "JHM": "Journal of the History of Medicine and allied Sciences",
    "JHPh": "Journal of the History of Philosophy",
    "JHS": "Journal of Hellenic Studies",
    "JHSex": "Journal of the history of sexuality",
    "JIES": "Journal of Indo-European Studies",
    "JJP": "Journal of Juristic Papyrology",
    "JMA": "Journal of Mediterranean archaeology",
    "JNES": "Journal of Near Eastern Studies",
    "JNG": "Jahrbuch f\u00fcr Numismatik und Geldgeschichte",
    "J\u00f6AI": "Jahreshefte des \u00d6sterreichischen Arch\u00e4ologischen Instituts",
    "J\u00f6Byz": "Jahrbuch der \u00d6sterreichischen Byzantinistik",
    "JPh": "Journal of Philosophy",
    "JPR": "Journal of prehistoric religion",
    "JR": "Journal of Religion",
    "JRA": "Journal of Roman archaeology",
    "JRGZ": "Jahrbuch des R\u00f6misch-Germanischen Zentralmuseums",
    "JRH": "Journal of Religious History",
    "JRMES": "Journal of Roman military equipment studies",
    "JRS": "Journal of Roman Studies",
    "JS": "Journal des Savants",
    "JSAH": "Journal of the Society of Architectural Historians",
    "JSGU": "Jahrbuch der Schweizerischen Gesellschaft f\u00fcr Ur- und Fr\u00fchgeschichte",
    "JSJ": "Journal for the study of Judaism: (in the Persian, Hellenistic and Roman period)",
    "JThS": "Journal of Theological Studies. Oxford, Clarendon Press",
    "JVEG": "Jaarbericht van het Voor-Aziatisch-Egyptisch Genootschap Ex Oriente Lux",
    "JWAG": "Journal of the Walters Art Gallery",
    "JWG": "Jahrbuch f\u00fcr Wirtschaftsgeschichte",
    "JWI": "Journal of the Warburg and Courtauld Institutes",
    "KantStud": "Kant-Studien: Philosophische Zeitschrift",
    "KGB": "Koldewey-Gesellschaft, Vereinigung f\u00fcr baugeschichtliche Forschung e. V. Bericht \u00fcber die Tagung f\u00fcr Ausgrabungswissenschaft und Bauforschung",
    "KIAM": "Kul'tura iskusstvo anticnogo mira",
    "KJ": "K\u00f6lner Jahrbuch f\u00fcr Vor- und Fr\u00fchgeschichte, hrsg. vom R\u00f6misch- Germanischen Museum und der Arch\u00e4ologischen Gesellschaft K\u00f6ln",
    "KSIA": "Kratkije soobseni\u00e2 Inst. arheol. Akad. Nauk SSSR",
    "L&S": "Lingua e stile",
    "LCM": "Liverpool Classical Monthly",
    "LEC": "Les \u00c9tudes Classiques",
    "LF": "Listy filologick\u00e9",
    "LibStud": "Libyan Studies",
    "Ling": "La linguistique",
    "LingBibl": "Linguistica Biblica: interdisziplin\u00e4re Zeitschrift f\u00fcr Theologie und Linguistik",
    "LMS": "Litt\u00e9rature, m\u00e9dicine, soci\u00e9t\u00e9",
    "LNV": "Litterae Numismaticae Vindobonenses",
    "LThPh": "Laval Th\u00e9ologique et Philosophique",
    "M&H": "Medievalia et Humanistica: studies in medieval and Renaissance society",
    "MA": "Le Moyen \u00c2ge: revue trimestrielle d'histoire et de philologie",
    "MAev": "Medium Aevum",
    "MAGS": "Mitteilungen der Arch\u00e4ologischen Gesellschaft Steiermark",
    "MAI": "M\u00e9moires de l'Acad\u00e9mie des Inscriptions et Belles Lettres",
    "MAIB": "Memorie dell'Accademia delle Scienze dell'Istituto di Bologna, Cl. di Sc. morali",
    "MAL": "Memorie della Classe di Scienze morali e storiche dell'Accademia dei Lincei",
    "MAT": "Memorie dell'Accademia delle Scienze di Torino, Classe di Scienze morali, storiche e filologiche",
    "MAWBL": "Mededelingen van de koninklijke Academie voor Wetensehappen, Letteren & Schone Kunsten van Belgi\u00eb, Kl. der Letteren",
    "MAZ": "Mainzer Arch\u00e4ologische Zeitschrift",
    "MBAH": "M\u00fcnsterische Beitr\u00e4ge zur antiken Handelsgeschichte",
    "MCr": "Museum Criticum",
    "MCSN": "Materiali e contributi per la storia della narrativa greco-latina",
    "MCV": "M\u00e9langes de la Casa de Vel\u00e1zquez, Madrid",
    "MD": "Materiali e discussioni per l'analisi dei testi classici",
    "MDAI(A)": "Mitteilungen des Deutschen Arch\u00e4ologischen Instituts (Athen. Abt.)",
    "MDAI(D)": "Damaszener Mitteilungen, hrsg. von dem Deutschen Arch\u00e4ologischen Institut (Station Damaskus)",
    "MDAI(I)": "Mitteilungen des Deutschen Arch\u00e4ologischen Instituts (Abt. Istambul)",
    "MDAI(M)": "Mitteilungen des Deutschen Arch\u00e4ologischen Instituts (Abt. Madrid)",
    "MDAI(R)": "Mitteilungen des Deutschen Arch\u00e4ologischen Instituts (R\u00f6m. Abt.)",
    "MedArch": "Mediterranean Archaeology: Australian and New Zealand journal for the archaeology of the Mediterranean world",
    "MedHist": "Medical History: a quarterly journal devoted to the history of medicine and related sciences",
    "MEFRA": "M\u00e9langes d'Arch\u00e9ologie et d'Histoire de l'\u00e9cole Fran\u00e7aise de Rome, Antiquit\u00e9",
    "MEFRM": "M\u00e9langes de l'\u00e9cole fran\u00e7aise de Rome. Moyen \u00c2ge et temps modernes",
    "MEG": "Medioevo greco",
    "MGM": "Milit\u00e4rgeschichtliche Mitteilungen",
    "MGR": "Miscellanea greca e romana: studi pubblicati dall'Ist. italiano per la storia antica",
    "MH": "Museum Helveticum: revue suisse pour l'\u00e9tude de l'Antiquit\u00e9 classique",
    "MHA": "Memorias de historia antigua",
    "MHJ": "Medizin-historisches Journal",
    "MHR": "Mediterranean Historical Review, ed. by the Aranne School of History, Tel Aviv Univ",
    "MiChA": "Mitteilungen zur christlichen Arch\u00e4ologie",
    "MIL": "Memorie dell'Ist. Lombardo, Accademia di Scienze e Lettere, Cl. di Lett., Sc. morali e storiche",
    "Minerva(lond)": "Minerva: the international review of ancient art and archaeology",
    "Minerva(vall)": "Minerva: revista de filolog\u00eda cl\u00e1sica",
    "MI\u00f6G": "Mitteilungen des Instituts f\u00fcr \u00f6sterreichische Geschichtsforschung",
    "MLatJB": "Mittellateinisches Jahrbuch",
    "MMAI": "Monuments et m\u00e9moires publi\u00e9s par l'Acad\u00e9mie des Inscriptions et Belles-Lettres (Fondation Piot)",
    "MMJ": "Metropolitan Museum Journal",
    "MNIR": "Mededelingen van het Nederlandsch historisch Instituut te Rome",
    "ModSch": "The Modern Schoolman: a quarterly Journal of Philosophy",
    "MonAL": "Monumenti antichi, pubblicati dall'Accademia dei Lincei",
    "MPAA": "Atti della Pontificia Accademia romana di Archeologia, Ser. IIIa, Memorie (in-4\u00a1)",
    "MPhL": "Museum Philologum Londiniense",
    "MS": "Mediaeval Studies",
    "MSR": "M\u00e9langes de Science Religieuse",
    "MSS": "M\u00fcnchener Studien zur Sprachwissenschaft",
    "MT": "Museum Tusculanum",
    "MusPat": "Museum Patavinum: rivista semestrale della Facolt\u00e0 di Lettere e Filosofia di Padova",
    "MZ": "Mainzer Zeitschrift: Mittelrheinisches Jahrbuch f\u00fcr Arch\u00e4ologie, Kunst und Geschichte",
    "NAC": "Numismatica e antichit\u00e0 classiche: quaderni ticinesi",
    "NAFM": "Nuovi annali della Facolt\u00e0 di Magistero dell'Universit\u00e0 di Messina",
    "NAWG": "Nachrichten der Akademie der Wissenschaften in G\u00f6ttingen, Philol.- Hist. Klasse",
    "NC": "Numismatic Chronicle",
    "NCirc": "Numismatic Circular",
    "NE": "Numismatika i \u00e8pigraphika",
    "NECN": "New England Classical Newsletter",
    "NL": "Numismatic Literature",
    "NNB": "Numismatisches Nachrichtenblatt: Organ des Verbandes der Dt. M\u00fcnzvereine",
    "NphM": "Neuphilologische Mitteilungen",
    "NRS": "Nuova rivista storica",
    "NRTh": "Nouvelle Revue Th\u00e9ologique",
    "NSA": "Notizie degli scavi di antichit\u00e0",
    "NT": "Novum Testamentum: an international quarterly for New Testament and related studies",
    "NTA": "New Testament Abstracts",
    "NTM": "Schriftenreihe f\u00fcr Geschichte der Naturwissenschaften, Technik und Medizin",
    "NTS": "New Testament Studies: an international journal publ. quarterly under the auspices of Studiorum Novi Testamenti Societas",
    "NZ": "Numismatische Zeitschrift",
    "OA": "Oriens Antiquus: rivista del Centro per le Antichit\u00e0 e la Storia dell'Arte del vicino Oriente",
    "OAth": "Opuscula Atheniensia: acta Inst. Athen. Regni Sueciae",
    "OC": "Oriens Christianus: Hefte f\u00fcr die Kunde des christlichen Orients",
    "OCP": "Orientalia Christiana Periodica",
    "OJA": "Oxford Journal of Archaeology",
    "OLP": "Orientalia Lovaniensia Periodica",
    "OLZ": "Orientalistische Literaturzeitung",
    "OMRL": "Oudheidkundige Mededelingen uit het Rijksmuseum van Oudheiden te Leiden",
    "ORom": "Opuscula Romana: acta Inst. Rom. Regni Sueciae",
    "OS": "Ostkirchliche Studien",
    "OSAPh": "Oxford Studies in Ancient Philosophy",
    "P&P": "Past and Present: a journal of historical Studies",
    "PAA": "Praktika tes Akademias Athenon",
    "PAAH": "Praktika tes en Athenais Archaiologikes Etaireias",
    "PACPhA": "Proceedings of the American Catholic Philosophical Association",
    "PalEQ": "Palestine Exploration Quarterly",
    "PAPHS": "Proceedings of the American Philosophical Society",
    "PAS": "Proceedings of the Aristotelian Society",
    "PAS(suppl)": "Proceedings of the Aristotelian Society. Supplementary volume.",
    "PBA": "Proceedings of the British Academy",
    "PBH": "Patma-banasirakan handes: revue historico-philologique",
    "PBSR": "Papers of the British School at Rome",
    "PCA": "Proceedings of the Classical Association",
    "PCPhS": "Proceedings of the Cambridge Philological Society",
    "PF": "The Philosophical Forum: a philosophical quarterly publ. with the cooper. of the Dept. of Philosophy of Boston Univ.",
    "Ph&Lit": "Philosophy and Literature",
    "Ph&PhenR": "Philosophy and Phenomenological Research",
    "Ph&Rh": "Philosophy and Rhetoric",
    "PhH": "Pharmacy in history",
    "PhilClass": "Philologia classica: recueil interuniversitaire p\u00e9riodique",
    "PhilosQ": "The Philosophical Quarterly",
    "PHist": "Przeglad Historyczny",
    "PhJ": "Philosophisches Jahrbuch",
    "PhLA": "Philosophischer Literaturanzeiger",
    "PhN": "Philosophia naturalis",
    "PhQ": "Philological Quarterly",
    "PhR": "Philosophical Review",
    "PhRdschau": "Philosophische Rundschau: eine Zeitschrift f\u00fcr philosophische Kritik",
    "PhStud": "Philosophical Studies",
    "PK": "Pam\u00e2tniki kul'tury (Monuments of culture: new discoveries)",
    "PKFil": "Pitann\u00e2 klasicno\u00ef filolog\u00ec\u00ef (Questions de philologie classique)",
    "PP": "La Parola del passato: rivista di studi antichi",
    "PPH": "Perspektiven der Philosophie: neues Jahrbuch",
    "PPol": "Il pensiero politico: rivista di storia delle idee politiche e sociali",
    "PRIA": "Proceedings of the Royal Irish Academy",
    "PSN": "Petronian Society Newsletter",
    "PVS": "Proceedings of the Virgil Society",
    "QAL": "Quaderni di archeologia della Libia",
    "QC": "Quaderni catanesi di studi classici e medievali",
    "QCCCM": "Quaderni catanesi di cultura classica e medievale",
    "QCTC": "Quaderni di Cultura e di Tradizione classica",
    "QFC": "Quaderni di filologia classica dell'Universit\u00e0 di Trieste, Ist. di Filol. class.",
    "QIASA": "Quaderni dell'Istituto di Archeologia e Storia antica dell'Univ. G. d'Annunzio, Chieti",
    "QIFP": "Quaderni dell'Ist. di Filosofia, Univ. degli Studi di Perugia, Fac. di Magistero",
    "QILL": "Quaderni dell'Istituto di Lingua e Letteratura latina. Universit\u00e0 di Roma, Fac. di Magistero",
    "QJS": "Quarterly Journal of Speech",
    "QLF": "Quaderni linguistici e filologici: ricerche svolte presso l'Univ. degli Studi di Macerata",
    "QMAB": "Quaderni del Museo archeologico F. Ribezzo di Brindisi",
    "QS": "Quaderni di storia",
    "QUCC": "Quaderni urbinati di cultura classica",
    "RA": "Revue arch\u00e9ologique",
    "RAAN": "Rendiconti dell'Accademia di Archeologia, Lettere e Belle Arti di Napoli",
    "RAC": "Rivista di archeologia cristiana",
    "RACF": "Revue arch\u00e9ologique du Centre [de la France]",
    "RAComo": "Rivista archeologica dell'antica provincia e diocesi di Como",
    "RAE": "Revue arch\u00e9ologique de l'Est et du Centre-Est",
    "RAIB": "Rendiconti dell'Accademia delle Scienze dell'Istituto di Bologna, Cl. di sc. mor",
    "RAL": "Rendiconti della Classe di Scienze morali, storiche e filologiche dell'Accademia dei Lincei",
    "RAN": "Revue arch\u00e9ologique de Narbonnaise",
    "RAPic": "Revue arch\u00e9ologique de Picardie",
    "RBA": "Revue belge d'arch\u00e9ologie et d'histoire de l'art",
    "RBen": "Revue b\u00e9n\u00e9dictine",
    "RBi": "Revue biblique",
    "RBN": "Revue belge de numismatique et de sigillographie",
    "RBPh": "Revue belge de philologie et d'histoire",
    "RBS": "Regulae Benedicti Studia: annuarium internationale",
    "RCCM": "Rivista di cultura classica e medioevale",
    "RD": "Revue historique de droit fran\u00e7ais et \u00e9tranger",
    "RdA": "Rivista di archeologia",
    "RDAC": "Report of the Department of Antiquities, Cyprus",
    "RdN": "Revue du Nord",
    "REA": "Revue des \u00e9tudes anciennes",
    "REArm": "Revue des \u00e9tudes arm\u00e9niennes",
    "REAug": "Revue des \u00e9tudes augustiniennes",
    "REByz": "Revue des \u00e9tudes byzantines",
    "REC": "Revista de estudios cl\u00e1sicos",
    "RecAug": "Recherches augustiniennes (Suppl\u00e9ment \u00e0 REAug)",
    "RecSR": "Recherches de science religieuse",
    "RecTh": "Recherches de th\u00e9ologie ancienne et m\u00e9di\u00e9vale",
    "REG": "Revue des \u00e9tudes grecques",
    "REgypt": "Revue d'\u00e9gyptologie",
    "REJ": "Revue des \u00e9tudes juives",
    "REL": "Revue des \u00e9tudes latines",
    "RELig": "Revue d'\u00e9tudes ligures",
    "RelStud": "Religious Studies",
    "RenQ": "Renaissance Quarterly",
    "REPh": "Revue de l'enseignement philosophique",
    "RESE": "Revue des \u00e9tudes sud-est europ\u00e9ennes",
    "REspLing": "Revista espa\u00f1ola de lingu\u00edstica",
    "RF(Argentina)": "Revista de filosof\u00eda",
    "RF(Bologna)": "Rivista di filosofia",
    "RFIC": "Rivista di filologia e di istruzione classica",
    "RFN": "Rivista di filosofia neoscolastica",
    "RH": "Revue historique",
    "RHD": "Revue d'histoire du droit (Tijdschrift voor Rechtsgeschiedenis)",
    "RHE": "Revue d'histoire eccl\u00e9siastique",
    "RhM": "Rheinisches Museum",
    "RHPHARM": "Revue d'histoire de la pharmacie",
    "RHPhR": "Revue d'histoire et de philosophie religieuses",
    "RHR": "Revue de l'histoire des religions",
    "RHS": "Revue d'histoire des sciences et de leurs applications",
    "RHT": "Revue d'histoire des textes",
    "RHum": "Roczniki humanistyczne. 3, Filologia klasyczna",
    "RHV": "Revue historique vaudoise",
    "RIA": "Rivista dell'Istituto Nazionale di Archeologia e Storia dell'Arte",
    "RicTeol": "Ricerche teologiche",
    "RIDA": "Revue internationale des droits de l'Antiquit\u00e9",
    "RIFD": "Rivista internazionale di filosofia del diritto",
    "RigBer": "Riggisberger Berichte",
    "RIL": "Rendiconti dell'Istituto Lombardo, Classe di Lettere, Scienze morali e storiche",
    "RIN": "Rivista italiana di numismatica e scienze affini",
    "RIO": "Revue internationale d'onomastique",
    "RIPh": "Revue internationale de philosophie",
    "RISSH": "Revue informatique et statistique dans les sciences humaines",
    "RivBibl": "Rivista biblica",
    "RJ": "Rechtshistoriches Journal",
    "RKI": "Report of the Keio Institute of Cultural and Linguistic Studies",
    "RL": "Revista de letras",
    "RLAC": "Reallexikon f\u00fcr Antike und Christentum",
    "RLAF": "Revista latinoamericana de filosof\u00eda",
    "RMeta": "Review of Metaphysics",
    "RMM": "Revue de m\u00e9taphysique et de morale",
    "RN": "Revue numismatique",
    "R\u00f6": "R\u00f6misches \u00f6sterreich: Jahresschrift der \u00d6sterreichischen Gesellschaft f\u00fcr Arch\u00e4ologie",
    "RocsHum": "Roczniki humanistyczne",
    "RomBarb": "Romanobarbarica: contributi allo studio dei rapporti culturali tra mondo latino e mondo barbarico",
    "RomForsch": "Romanische Forschungen: Vierteljahresschrift f\u00fcr romanische Sprachen und Literaturen",
    "RPAA": "Rendiconti della Pontificia Accademia di Archeologia",
    "RPh": "Revue de philologie, de litt\u00e9rature et d'histoire anciennes",
    "RPhA": "Revue de philosophie ancienne",
    "RPhilos": "Revue philosophique de la France et de l'\u00e9tranger",
    "RPhL": "Revue philosophique de Louvain",
    "RPL": "Res publica litterarum: studies in the classical tradition",
    "RQA": "R\u00f6mische Quartalschrift f\u00fcr christliche Altertumskunde und f\u00fcr Kirchengeschichte",
    "RQS": "Revue des questions scientifiques",
    "RS": "Revue de synth\u00e8se",
    "RSA": "Rivista storica dell'Antichit\u00e0",
    "RSAA": "Revue suisse d'art et d'arch\u00e9ologie",
    "RSBN": "Rivista di studi bizantini e neoellenici",
    "RSBS": "Rivista di studi bizantini e slavi",
    "RSCI": "Rivista di storia della Chiesa in Italia",
    "RSF": "Rivista critica di storia della filosofia",
    "RSI": "Rivista storica italiana",
    "RSLR": "Rivista di storia e letteratura religiosa",
    "RSO": "Rivista degli studi orientali",
    "RSP": "Rivista di studi pompeiani",
    "RSPh": "Revue des sciences philosophiques et th\u00e9ologiques",
    "RSR": "Revue des sciences religieuses",
    "RSS": "Rassegna storica salernitana",
    "RStudFen": "Rivista di studi fenici, pubbl. dal Centro di studio per la civilt\u00e0 fenicia e punica",
    "RThL": "Revue th\u00e9ologique de Louvain",
    "RThPh": "Revue de th\u00e9ologie et de philosophie",
    "RUB": "Revue de l'Universit\u00e9 de Bruxelles",
    "Rudiae": "Rudiae: ricerche sul mondo classico",
    "RVF": "Revista venezolana de filosof\u00eda",
    "S&C": "Scrittura e Civilt\u00e0",
    "SA": "Sovetskaja arheologia",
    "SAMPhN": "Newsletter of the Society for ancient medicine and pharmacy",
    "SAWDDR": "Sitzungsberichte der Akademie der Wissenschaften in Berlin, Gesellschaftswissenschaften (G)",
    "SAWW": "Sitzungsberichte der \u00d6sterreichischen Akademie der Wissenschaft in Wien, Philos.-Hist. Klasse",
    "SBAW": "Sitzungsberichte der Bayerischen Akademie der Wissenschaften, Philos.- Hist. Klasse",
    "SBB": "Studien zum Buch- und Bibliothekswesen",
    "SCent": "The second century: a journal of early Christian studies",
    "SCI": "Scripta classica Israelica: yearbook of the Israel Soc. for the promotion of classical Studies",
    "SCO": "Studi classici e orientali",
    "SDHI": "Studia et Documenta Historiae et Iuris",
    "SE": "Studi etruschi. Roma, Giorgio Bretschneider",
    "SEJG": "Sacris Erudiri: jaarboek voor Godsdienstwetenschappen",
    "SemRom": "Seminari romani di cultura greca",
    "SG": "Studi genuensi",
    "SGE": "Soobseni\u00e2 Gosudarstvennogo \u00c8rmitaza (Reports of the Hermitage Museum)",
    "SHAW": "Sitzungsberichte der Heidelberger Akademie der Wissenschaften, Philos.- Hist. Klasse",
    "SHHA": "Studia historica historia antigua",
    "SHPS": "Studies in history and philosophy of science",
    "SicGymn": "Siculorum Gymnasium: rassegna semestrale della Facolt\u00e0 di Lettere e Filosofia dell'Universit\u00e0 di Catania",
    "SIFC": "Studi italiani di filologia classica",
    "SILTA": "Studi italiani di linguistica teorica e applicata",
    "SJ": "Saalburg-Jahrbuch",
    "SL": "Studia linguistica: revue de linguistique g\u00e9n\u00e9rale et compar\u00e9e",
    "SMEA": "Studi micenei ed egeo-anatolici",
    "SMed": "Schede medievali: rassegna a cura dell'officina di studi medievali",
    "SMSR": "Studi e materiali di storia delle religioni",
    "SNR": "Schweizerische numismatische Rundschau",
    "SO": "Symbolae Osloenses, auspiciis Societatis Graeco-Latine",
    "SOliv": "Studia Oliveriana",
    "SPFB": "Sborn\u00edk Prac\u00ed Filosofick\u00e9 Fak. Brnensk\u00e9 Univ. Rada archeol. klas.",
    "SPFB(klas)": "Sborn\u00edk Prac\u00ed Filosofick\u00e9 Fakulty Brnensk\u00e9 University",
    "SPh": "Studies in Philology",
    "SPhP": "Symbolae Philologorum Posnanensium",
    "SPhS": "Studia philologica Salmanticensia. Univ. de Salamanca, Acta Salm. Filos. y Letras",
    "Sprachkunst": "Sprachkunst. Beitr\u00e4ge zur Literaturwissenschaft",
    "SR": "Studies in religion (Sciences religieuses)",
    "SRIC": "Studi e ricerche dell'Ist. di Civilit\u00e0 classica, cristiana, medievale",
    "SS": "Studi sardi",
    "SSL": "Studi e saggi linguistici",
    "SStor": "Storia della storiografia",
    "STh": "Scandinavian Journal of Theology",
    "STHist": "Sources: travaux historiques",
    "StudClas": "Studii Clasice",
    "StudLang": "Studies in Language: international journal sponsored by the Foundations of Language",
    "StudMagr": "Studi magrebini",
    "StudMed": "Studi medievali",
    "StudMon": "Studia monastica",
    "StudOv": "Studium Ovetense: revista del Centro sup. de EStudios eclesi\u00e1sticos La Asunci\u00f3n",
    "StudPat": "Studia Patavina: rivista di scienze religiose",
    "StudPhil": "Studia philosophica: annuaire de la Soci\u00e9t\u00e9 suisse de philosophie",
    "StudPhilon": "The Studia Philonica Annual: studies in Hellenistic Judaism",
    "StudPic": "Studia Picena",
    "StudRom": "Studi romani: rivista bimestrale dell'Istituto di Studi Romani",
    "StudRomagn": "Studi romagnoli",
    "StudSal": "Studi salentini",
    "StudStor": "Studi storici: rivista trimestrale dell'Ist. Gramsci",
    "StudUrb(B)": "Studi urbinati di storia, filosofia e letteratura",
    "Stylus": "Stylus: cuadernos de filolog\u00eda",
    "SyllClass": "Syllecta classica",
    "SZ": "Studia Zamorensia",
    "SZG": "Schweizerische Zeitschrift f\u00fcr Geschichte",
    "T&C": "Technology and Culture",
    "T&MBYZ": "Travaux et m\u00e9moires du Centre de recherches d'hist. et civil. byzantines",
    "TAPhA": "Transactions and Proceedings of the American Philological Association",
    "TAPhS": "Transactions of the American Philosophical Society",
    "TCLA": "Travaux du Cercle linguistique d'Aix-en-Provence",
    "T\u00c8": "Trudy gosudarstbennogo \u00c8rmitaza (travaux du Mus\u00e9e d'\u00c9tat de l'Ermitage)",
    "TF": "Tijdschrift voor filosofie",
    "TG": "Tijdschrift voor geschiedenis",
    "Th&Ph": "Theologie und Philosophie",
    "Theoria": "Theoria: a Swedish journal of philosophy and psychology",
    "ThLZ": "Theologische Literaturzeitung: Monatsschrift f\u00fcr das gesamte Gebiet der Theologie und Religionswissenschaft",
    "ThQ": "Theologische Quartalschrift",
    "ThRdschau": "Theologische Rundschau",
    "ThRev": "Theologische Revue",
    "ThS": "Theological Studies",
    "ThZ": "Theologische Zeitschrift",
    "TJ": "Trinity Journal, publ. by Trinity Evangelical Divinity School",
    "TLS": "The Times Literary Supplement",
    "TMon": "Tr\u00e9sors mon\u00e9taires",
    "Topoi(Dordrecht)": "Topoi: an international review of philosophy",
    "Topoi(Lyon)": "Topoi: Orient-Occident",
    "TPhS": "Transactions of the Philological Society",
    "TR": "Le Temps de la r\u00e9flexion",
    "TraNeL": "Travaux neuch\u00e2telois de linguistique",
    "TZ": "Trierer Zeitschrift, f\u00fcr Geschichte und Kunst des Trierer Landes und seiner Nachbargebiete",
    "UF": "Ugarit-Forschungen",
    "V&F": "Verkundigung und Forschung: Wissenschaft vom Neuen Testament. Beitr. zu Evangelische Theologie",
    "VChr": "Vigiliae Christianae: a review of early Christian life and language",
    "VDI": "Vestnik Drevnej Istorii (Revue d'Histoire ancienne)",
    "Veleia": "Veleia: revista de prehistoria, historia antigua, arqueolog\u00e1 y filolog\u00eda cl\u00e1sicas",
    "Verbum": "Verbum: revue de linguistique publ. par l'Univ. de Nancy II",
    "VetChr": "Vetera Christianorum",
    "Vichiana": "Vichiana: rassegna di studi filologici e storici",
    "Vivarium": "Vivarium: a journal for mediaeval philosophy and the intellectual life of the Middle Ages",
    "VKF": "Voprosy klassiceskoj Filologii",
    "VL": "Vita Latina",
    "VLUFILOS": "Vestnik Leningradskogo Universiteta, Ser. 6, Filos.",
    "VLUIST": "Vestnik Leningradskogo Universiteta, Ser. 2, Istor.",
    "VMUFILOL": "Vestnik Moskovskogo Universiteta (filol. sekcija)",
    "VMUFILOS": "Vestnik Moskovskogo Universiteta (filos. sekcija)",
    "VMUIST": "Vestnik Moskovskogo Universiteta (ist. sekcija)",
    "Vop\u00e5z": "Voprosy \u00e2zykoznani\u00e2 (Probl\u00e8mes de linguistique)",
    "VopFilos": "Voprosy filosofii (Probl\u00e8mes de philosophie)",
    "VopIst": "Voprosy istorii (Probl\u00e8mes d'histoire)",
    "VoxLat": "Vox Latina: commentarii periodici",
    "VoxP": "Vox Patrum",
    "VR": "Vox Romanica: annales Helvetici explorandis Linguis Romanicis destinati",
    "VRel": "Visible Religion: annual for religious iconography",
    "VT": "Vetus Testamentum: quarterly publ. by the International Organization of Old Testament Scholars",
    "W&D": "Wort und Dienst: Jahrbuch der kirchlichen Hochschule Bethel (bei Bielefeld)",
    "WHB": "Wiener humanistische Bl\u00e4tter",
    "WJA": "W\u00fcrzburger Jahrb\u00fccher f\u00fcr die Altertumswissenschaft",
    "WO": "Die Welt des Orients: wissenschaftliche Beitr\u00e4ge zur Kunde des Morgenlandes",
    "WS": "Wiener Studien: Zeitschrift f\u00fcr klassische Philologie und Patristik",
    "WZBERLIN": "Wissenschaftliche Zeitschrift der Humboldt-Univ. Berlin, Gesellsch.- & sprachwiss. Reihe",
    "WZGREIFS": "Wissenschaftliche Zeitschrift der Ernst-Moritz-Arndt-Univ., Greifswald, Gesellsch.- & sprachwiss. Reihe.",
    "WZHALLE": "Wissenschaftliche Zeitschrift der Martin-Luther-Univ. Halle-Wittenberg",
    "WZJENA": "Wissenschaftliche Zeitschrift der Friedrich-Schiller-Univ. Jena, Gesellsch.- & sprachwiss. Reihe.",
    "WZLEIPZIG": "Wissenschaftliche Zeitschrift der Karl-Marx-Univ. Leipzig, Gesellsch.- & sprachwlss. Reihe.",
    "WZROSTOCK": "Wissenschaftliche Zeitschrift der Wilhelm-Pieck-Univ. Rostock Gesellsch.- & sprachwiss. Reihe.",
    "YCIS": "Yale Classical Studies",
    "YJC": "The Yale Journal of Criticism",
    "YLG": "Yale University Library Gazette",
    "ZAC": "Zeitschrift f\u00fcr antikes Christentum",
    "ZAnt": "Ziva Antika (Antiquit\u00e9 vivante)",
    "ZAS": "Zeitschrift f\u00fcr \u00e4gyptische Sprache und Altertumskunde",
    "ZATW": "Zeitschrift f\u00fcr die Alttestamentliche Wissenschaft",
    "ZBB": "Zentralblatt f\u00fcr Bibliothekswesen",
    "ZDMG": "Zeitschrift der Deutschen Morgenl\u00e4ndischen Gesellschaft",
    "ZfA": "Zeitschrift f\u00fcr Arch\u00e4ologie",
    "ZJKF": "Zpr\u00e1vy Jednoty Klasickaych Filologu",
    "ZKG": "Zeitschrift f\u00fcr Kirchengeschichte",
    "ZKTh": "Zeitschrift f\u00fcr Katholische Theologie",
    "ZNTW": "Zeitschrift f\u00fcr die Neutestamentliche Wissenschaft und die Kunde der \u00e4lteren Kirche",
    "ZPalV": "Zeitschrift des Deutschen Pal\u00e4stina-Vereins",
    "ZPE": "Zeitschrift f\u00fcr Papyrologie und Epigraphik",
    "ZPhF": "Zeitschrift f\u00fcr Philosophische Forschung",
    "ZRG": "Zeitschrift der Savigny-Stiftung f\u00fcr Rechtsgeschichte (Romanistische Abteilung)",
    "ZRGG": "Zeitschrift f\u00fcr Religions- und Geistesgeschichte",
    "ZRPh": "Zeitschrift f\u00fcr Romanische Philologie",
    "ZS": "Zeitschrift f\u00fcr Semiotik",
    "ZVS": "Zeitschrift f\u00fcr Vergleichende Sprachforschung",
    "ZWG": "Sudhoffs Archiv: Zeitschrift f\u00fcr Wissenschaftsgeschichte"
}